builds:
  - binary: sshst
    goarch: [amd64]
    goos: [darwin, linux]
    dir: cmd
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^.github:'
nfpms:
  - vendor: ssh.st
    homepage: https://ssh.st
    maintainer: ssh.st team <ssh.st@ssh.st>
    description: TODO
    formats: [deb]
brews:
  - github:
      owner: sshst
      name: homebrew-taps
    commit_author:
      name: Aidan Steele
      email: aidan.steele@glassechidna.com.au
    homepage: https://ssh.st
    description: TODO
#scoop:
#  bucket:
#    owner: sshst
#    name: scoop-bucket
#  commit_author:
#    name: Aidan Steele
#    email: aidan.steele@glassechidna.com.au
#  url_template: "http://downloads-ap-southeast-2.ssh.st/scoop/{{ .ArtifactName }}"
#  homepage: https://ssh.st
#  description: TODO
